title: bleu
author: Chris Su
email_obfuscated: "chrjs @ cmu . edu"
subtitle: bomp
description: Notes on computer science, AI, and mathematics by Chris Su at Carnegie Mellon University (CMU).
affiliation: Carnegie Mellon University (CMU)
author_box: Chris Su - < chrjs @ cmu . edu >
url: https://www.chrissuu.com

baseurl: "/bleu"
destination: ./_site/bleu

profile-picture: assets/pngwing.com.png
favicon_location: assets/sky.png

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"

markdown: kramdown
highlighter: rouge

keywords:
  - Chris Su
  - CMU
  - Carnegie Mellon University
  - computer science blog
  - AI
  - mathematics

defaults:
  - scope:
      path: ""
      type: posts
    values:
      author: Chris Su
